### ISSUE TITLE
Dark mode flicker in Chrome

### ISSUE THREAD

**Issue by christophersjchow** [flexdinesh/blogster#9]
I've noticed that in Chrome (macOS 109.0.5414.87) there is a flickering when navigating between pages only for the production build. In dev mode this doesn't seem to occur nor does it occur in Safari for the production build.

Here's a video showing the issue:

https://user-images.githubusercontent.com/47544496/214039411-00eb8ea9-d7c3-494c-9433-68b346def6ac.mov

**Comment by flexdinesh** [comment]
oh man Chrome is doing its own resource prioritization again. It's happening in my blog too https://dineshpandiyan.com. I will see what's going on this week. We probably might have to preload the critical stylesheet or use js and set the css vars in `:root`.

**Comment by flexdinesh** [comment]
Just fixed this theme flash issue in this commit https://github.com/flexdinesh/blogster/commit/4f275e8550b683241afae2d80af9531fdb06a8cf

The root cause was the background-color transition style we had `transition: background-color 0.3s ease;`. Chrome was adding a transition to the color even on first paint while firefox did not. Either way, lesson learnt - do not use bg color transition on page load for non-white backgrounds or Chrome will flash white once.
